# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  # readdocs master now includes a rust toolchain
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    rust: "1.55"

python:
  install:
    - method: pip
      path: .
